parameters:

services:
    projet_locale.locale_listener:
        class: Projet\FirstBundle\EventListner\LocaleListener
        arguments: ["%kernel.default_locale%",@fos_facebook.api,@service_container]
        tags:
            - { name: kernel.event_subscriber, priority: 100 }
        
    session.storage.native:
        class:     Projet\FirstBundle\Session\SessionStorage
        arguments: [%session.storage.options%, @service_container]